version: '3.8'

services:
    backendPG:
        image: postgres:latest
        container_name: backengPG
        environment:
            - POSTGRES_USER=backend
            - POSTGRES_PASSWORD=backend1!
            - POSTGRES_DB=work_db
        ports:
            - "5432:5432"
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge