/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatArea: typeof import('./components/ChatArea.vue')['default']
    ContactList: typeof import('./components/ContactList.vue')['default']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    MessageTextArea: typeof import('./components/MessageTextArea.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
