/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactList: typeof import('./components/ContactList.vue')['default']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
